---
title: "JF_processing"
output: html_document
---

```{r setup, include=F, warning=F}

knitr::opts_chunk$set(echo = TRUE)




library(tidyverse)
library(lubridate)
library(chron)
library(formattable)
library(gridExtra)
library(kableExtra)
library(RHESSysIOinR)
library(data.table)
library(stringr)
library(beepr)
# function used to aggregate daily data to water year
# many of the relationships we are interested in can't be seen if we look at daily output
# because of time lags - aggregating by water year makes many of these more visible
# note relationships are also "better" if we use water year rather than calendar year
# because of the time lags and  seasonality of precipitation and active growing season
resthinagg2 = function(resthin.tmp) {
  
  # note that for stores (plantc) we use average
  # for fluxes (et, watertransfer, evap, trans, psn) we use sum
  # for some variables we look at annual maximum (pkswe) and maxcpool 
resthin.tmp.wy = resthin.tmp %>% 
  group_by(scen,climproj,wy,thin) %>% 
  dplyr::summarize(
         plantc=mean(plantc, na.rm=T),
         stemc_live= mean(stemc_live),
         stemc_dead=mean(stemc_dead),
         lai=mean(lai),
         trans=sum(trans),
         evap=sum(evap), 
         gpsn=sum(gpsn), 
         resp=sum(resp), 
         precip=sum(precip),
         maxcpool=max(cpool),
         streamflow=sum(streamflow),
         tmin=min(tmin),
         tmax=max(tmax),
         tmin_avg=mean(tmin),
         tmax_avg=mean(tmax)
         ) 

resthin.tmp.wy$et = resthin.tmp.wy$evap+resthin.tmp.wy$trans
# pcpool is an indicator of drought stress (what percent of the plant carbon is in stored
# carbohydrate (cpool)
resthin.tmp.wy$pcpool = with(resthin.tmp.wy, ifelse(plantc > 0, maxcpool/plantc,0))

# design a variable to track how long its been since the 'thinning' even occured
resthin.tmp.wy = mutate(resthin.tmp.wy, wyg=wy-scen)


return(resthin.tmp.wy)
} 


### function for simulating thinning
init_thin <- function (thin) {
  
  # define proportions
  c <- thin
  t <- 1 - thin
  
  thinned <- data %>% 
    dplyr::filter(canopy == 'thin')
  
  control <- data  %>% 
    dplyr::filter(canopy == 'control')
   
  both <- data.frame(matrix(nrow = nrow(thinned), ncol = length(thinned)+1))
  names(both) <- c(names(thinned), 'thin')
  
  both$evap <- thinned$evap*t + control$evap*c
  both$trans <- thinned$trans*t +  control$trans*c
  both$gpsn <- thinned$gpsn*t + control$gpsn*c
  both$resp <- thinned$resp*t + control$resp*c
  both$lai <- thinned$lai*t +  control$lai*c
  both$cpool <- thinned$cpool*t + control$cpool*c
  both$plantc <- thinned$plantc*t + control$plantc*c
  both$stemc_live <- thinned$stemc_live*t + control$stemc_live*c
  both$stemc_dead <- thinned$stemc_dead*t + control$stemc_dead*c
  both$streamflow <- thinned$streamflow*t + control$streamflow*c
  both$thin <- thin*100
  both$wyg <- thinned$wyg
  both$climproj <- thinned$climproj
  both$level <- thinned$level
  both$scen <- thinned$scen
  both$year <- thinned$year
  both$month <- thinned$month
  both$day <- thinned$day
 
  
  return(both)
}



```



```{r preprocessing, include=F}

### read in climate projection runs
#create list of file suffixes for reading in with for loop
climscen <- c('rcp45-Had', 'rcp45-MIROC', 'rcp45-CNRM', 'rcp45-CAN', 'rcp85-Had', 'rcp85-MIROC', 'rcp85-CNRM', 'rcp85-CAN', 'historic')

# read in the data
for (i in 1:length(climscen)) {
  
  data <- read.table(sprintf('/Users/kmonper/Google Drive/JDSF/rhessys/out/JF_thin-proj-%s', climscen[i]), header = T)
  data <- select(data, -thin)
  #perform thinning
  tmp <- lapply(seq(0,1,.2), init_thin)
  thinned <- rbindlist(tmp)
  
  date <- mkdate(thinned)
  res <- resthinagg2(date)
  
  if (str_detect(climscen[i], '45')) {
    res$level <- 'RCP-45'
  } else if(str_detect(climscen[i], '85')) {
    res$level <- 'RCP-85'
  } else {
    res$level <- 'historic'
  }
  
  
  if (i == 1) {
  thin_full <- res
  } else {
    thin_full <- bind_rows(thin_full, res)
    }
  
  rm(res, tmp, data, date, thinned)
  print(i)
}


# subset data by projection level
rcp45 <- dplyr::filter(thin_full, level == 'RCP-45')
rcp85 <- dplyr::filter(thin_full, level == 'RCP-85')


```



```{r read climate data, include = F}
###
# clim file names
clim <- c('rcp45-Had', 'rcp45-MIROC', 'rcp45-CAN', 'rcp45-CNRM', 'rcp85-Had', 'rcp85-MIROC', 'rcp85-CAN', 'rcp85-CNRM', 'JF')

for (i in 1:length(clim)) {
  # read in data
  tmp = read_rhessys_met(sprintf("/Users/kmonper/Google Drive/JDSF/rhessys/clim/%s", clim[i]))
  # id projection
  tmp$climproj <- clim[i]
  
  if (str_detect(clim[i], '45')) {
    tmp$level <- 'rcp-4.5'
  } else if (str_detect(clim[i], '85')) {
    tmp$level <- 'rcp-8.8'
  } else {
    tmp$level <- 'historic'
  }
  
  if (i ==1) { 
    met <- tmp
  } else {
      met <- bind_rows(met, tmp)
    }
}
```



```{r ColorScales, echo = F}
cc <- scales::seq_gradient_pal("grey", "darkblue", "Lab")(seq(0,1,length.out=length(unique(thin_full$thin))))
cc[6] <- "red"
lbs <- as.character(unique(thin_full$thin))
lbs[lbs==100] <- "Control"

theme_set(theme_bw())
```
  
```{r, echo = F}
tmp <- mkdate(met)

temps <- tmp %>% 
  ungroup() %>%
  filter(climproj != 'JF') %>% 
  select(date, tmin, tmax, climproj) %>% 
  gather(unit, value, - date, -climproj)

ggplot(temps, aes(x = date, y = value, group = unit, color = unit)) +
  geom_line(alpha = .5) +
  facet_wrap(~climproj) + 
  labs(
    x = 'date',
    y = 'temp',
    title = 'yearly min and max temperatures for each model'
  )
```


***  
***  

## Carbon


```{r plant carbon, echo=F}
plantc <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(plantc),
    sd = sd(plantc)
  )

plantc_plot <- ggplot(plantc, aes(x=wyg, y=mean, group = level, color = level, fill = level)) +
  geom_line()  +
  geom_hline(yintercept = plantc$mean[plantc$thin==100 & plantc$wyg == 0], color = 'darkgreen', size = 1) + # do we want to visually compare against starting value of the control, or the mean, or...?
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd, fill = level), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'mean plant carbon across models',
    title = 'change in plant carbon over time by thinning'
  )
plantc_plot
```
  
  
#### dead and live stemc

```{r stem carbon, echo = F}
stemc <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(stemc_live),
    sd = sd(stemc_live)
  )

stemc_plot <- ggplot(stemc, aes(x=wyg, y=mean, group = level, fill = level)) +
  geom_line() +
  geom_hline(yintercept = stemc$mean[stemc$thin==100 & stemc$wyg == 0], color = 'darkgreen', size = 1) + 
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'stem carbon',
    title = 'change in stem carbon over time by thinning %'
  )
stemc_plot
```


```{r stem carbon dead, echo = F}
stemc_dead <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(stemc_dead),
    sd = sd(stemc_dead)
  )

stemc_plot <- ggplot(stemc_dead, aes(x=wyg, y=mean, group = level, fill = level)) +
  geom_line() +
  geom_hline(yintercept = stemc_dead$mean[stemc_dead$thin==100 & stemc_dead$wyg == 0], color = 'darkgreen', size = 1) + # do we want to visually compare against starting value of the control, or the mean, or...?
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'stem carbon',
    title = 'change in dead stem carbon over time by thinning %'
  )
stemc_plot
```

```{r, echo = F}
thin_full$stemc_total <- thin_full$stemc_dead+thin_full$stemc_live

stemc_tot <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(stemc_total),
    sd = sd(stemc_total)
  )

stemc_plot <- ggplot(stemc_tot, aes(x=wyg, y=mean, group = level, fill = level)) +
  geom_line() +
  geom_hline(yintercept = stemc_tot$mean[stemc_tot$thin==100 & stemc_tot$wyg == 0], color = 'darkgreen', size = 1) + # do we want to visually compare against starting value of the control, or the mean, or...?
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'stem carbon',
    title = 'change in TOTAL stem carbon over time by thinning %'
  )
stemc_plot

```
  

```{r, echo = F}
flux <- thin_full %>% 
  group_by(wyg, thin, climproj) %>% 
  summarise(
    mean = mean(stemc_total),
    sd = sd(stemc_total)
  )

ggplot(flux, aes(wyg, mean, group = as.factor(thin), fill = as.factor(thin))) +
  geom_line() +
  facet_wrap(~climproj) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd), alpha = .3)  +
  labs(
    x = 'years after thin',
    y = 'stem carbon',
    title = 'change in total stem carbon over time by model'
  )
```
    
    
  total plant carbon (Kg/m2) for each climate scenario based on thinning. precip is cumulative across all 100 years
```{r, echo=F, warning=F, message=F}
summary <- flux %>% 
  ungroup() %>% 
  filter(wyg == 79) %>% 
  mutate(mean = round(mean/1000,0)) %>% 
  select(-wyg, -sd) %>% 
  spread(thin, mean) %>% 
  arrange(-`100`)

met_sum <- met %>% 
  group_by(climproj) %>% 
  summarise(
    total_precip = sum(rain)
  )
met_sum$climproj[met_sum$climproj == 'JF'] <- 'historic'

ext <- left_join(summary, met_sum)

kable(ext) %>% 
  kable_styling()
```

***

## streamflow

```{r, echo = F}
thin_sub <- c(0,100)

stream45 <- filter(rcp45, thin %in% thin_sub)

ggplot(stream45, aes(x = wyg, y = streamflow, levels = thin, color = as.factor(thin))) +
  geom_line() +
  facet_wrap(~climproj)
```

```{r, echo = F}

stream85 <- filter(rcp85, thin %in% thin_sub)

ggplot(stream85, aes(x = wyg, y = streamflow, levels = thin, color = as.factor(thin))) +
  geom_line() +
  facet_wrap(~climproj)
```