---
title: "JF_processing"
output: html_document
---

```{r setup, include=FALSE, warning=F}

knitr::opts_chunk$set(echo = TRUE)




library(tidyverse)
library(lubridate)
library(chron)
library(formattable)
library(gridExtra)
library(kableExtra)
library(RHESSysIOinR)
library(data.table)
library(stringr)
library(beepr)
# function used to aggregate daily data to water year
# many of the relationships we are interested in can't be seen if we look at daily output
# because of time lags - aggregating by water year makes many of these more visible
# note relationships are also "better" if we use water year rather than calendar year
# because of the time lags and  seasonality of precipitation and active growing season
resthinagg = function(resthin.tmp) {
  
  # note that for stores (plantc) we use average
  # for fluxes (et, watertransfer, evap, trans, psn) we use sum
  # for some variables we look at annual maximum (pkswe) and maxcpool 
resthin.tmp.wy = resthin.tmp %>% 
  group_by(scen,thin,climproj,wy) %>% 
  dplyr::summarize(
         plantc=mean(plantc, na.rm=T),
         stemc= mean(stemc),
         lai=mean(lai),
         trans=sum(trans),
         evap=sum(evap), 
         gpsn=sum(gpsn), 
         resp=sum(resp), 
         precip=sum(precip),
         maxcpool=max(cpool)
         #, pkswe=max(snow),streamflow=sum(streamflow)
         ) 

resthin.tmp.wy$et = resthin.tmp.wy$evap+resthin.tmp.wy$trans
# pcpool is an indicator of drought stress (what percent of the plant carbon is in stored
# carbohydrate (cpool)
resthin.tmp.wy$pcpool = with(resthin.tmp.wy, ifelse(plantc > 0, maxcpool/plantc,0))
resthin.tmp.wy = mutate(resthin.tmp.wy, drought = ifelse(wy %in% c(2012:2015),TRUE, FALSE) )
# design a variable to track how long its been since the 'thinning' even occured
resthin.tmp.wy = mutate(resthin.tmp.wy, wyg=wy-scen)

# clear a variable to denote which soil type it is
resthin.tmp.wy$soil = resthin.tmp$soil[1]


return(resthin.tmp.wy)
} 
```



```{r preprocessing, include = F}


### read in climate projection runs

#create list of file suffixes for reading in with for loop
climscen <- c('rcp45-Had', 'rcp45-MIROC', 'rcp45-CNRM', 'rcp45-CAN', 'rcp85-Had', 'rcp85-MIROC', 'rcp85-CNRM', 'rcp85-CAN')

# read in the data
for (i in 1:length(climscen)) {
  
  tmp <- read.table(sprintf('/Users/kmonper/Google Drive/JDSF/rhessys/out/JF_thin-proj-400-%s.txt', climscen[i]), header = T)
  date <- mkdate(tmp)
  scen.wy <- resthinagg(date)
  
  if (str_detect(climscen[i], '45')) {
    scen.wy$level <- 'RCP-45'
  } else {
    scen.wy$level <- 'RCP-85'
  }

  if (i == 1) {
  thin_all <- scen.wy
  } else {
    thin_all <- bind_rows(thin_all, scen.wy)
    }
  
  print(i)
}
beep(3)
#remove 2030 scenario to make facet_wrapping neater
thin_proj <- filter(thin_all, scen != '2090')

# convert climate scenario years to`values
# thin_all$scen <- recode(thin_all$scen,
#                "2035" = 1,
#                "2040" = 2,
#                '2045' = 3,
#                '2050' = 4,
#                '2055' = 5,
#                '2060' = 6,
#                '2065' = 7,
#                '2070' = 8,
#                '2075' = 9,
#                '2080' = 10,
#                '2085' = 11,
#                '2090' = 12)

# subset data by projection level
rcp45 <- filter(thin_proj, level == 'RCP-45')
rcp85 <- filter(thin_proj, level == 'RCP-85')





# read in historical runs
base <- read.table("/Users/kmonper/Google Drive/JDSF/rhessys/out/JF_thin_2006.txt", header=T)
base <- mkdate(base)
base <- resthinagg(base)
base$level <- 'historic'
#remove 1 'NA'
base <- filter(base, scen != '2090')

# base$scen <- recode(base$scen,
#                "2035" = 1,
#                "2040" = 2,
#                '2045' = 3,
#                '2050' = 4,
#                '2055' = 5,
#                '2060' = 6,
#                '2065' = 7,
#                '2070' = 8,
#                '2075' = 9,
#                '2080' = 10,
#                '2085' = 11,
#                '2090' = 12)


#combine all
thin_full <- bind_rows(thin_proj, base)



```

```{r read climate data}
###
# clim file names
clim <- c('rcp45-Had', 'rcp45-MIROC', 'rcp45-CAN', 'rcp45-CNRM', 'rcp85-Had', 'rcp85-MIROC', 'rcp85-CAN', 'rcp85-CNRM', 'JF')

for (i in 1:length(clim)) {
  # read in data
  tmp = read_rhessys_met(sprintf("/Users/kmonper/Google Drive/JDSF/rhessys/clim/%s", clim[i]))
  # id projection
  tmp$climproj <- clim[i]
  
  if (str_detect(clim[i], '45')) {
    tmp$level <- 'rcp-4.5'
  } else if (str_detect(clim[i], '85')) {
    tmp$level <- 'rcp-8.8'
  } else {
    tmp$level <- 'historic'
  }
  
  if (i ==1) { 
    met <- tmp
  } else {
      met <- bind_rows(met, tmp)
    }
}
```



```{r ColorScales, echo = F}
cc <- scales::seq_gradient_pal("grey", "darkblue", "Lab")(seq(0,1,length.out=length(unique(thin_full$thin))))
cc[6] <- "red"
lbs <- as.character(unique(thin_full$thin))
lbs[lbs==100] <- "Control"

theme_set(theme_bw())
```
  
  
## Precip
```{r rainfall, echo = F}
# Figure 3 - rainfall
precip <- ggplot(base, 
          aes(x=wyg, y=precip, fill=precip))+
  geom_col()+
  labs(y="Precipition (mm/yr)", x="Year after thin", fill="Precip (mm/yr)") + 
  facet_wrap(~scen, nrow=4) +
  #theme(legend.position= c(0.05,0.01), legend.direction = "horizontal") + 
  guides(fill=guide_legend(title.position="top")) + 
  scale_fill_gradient(low="yellow", high="darkblue") +
  labs(title = 'precip data for historic run')
precip
```

```{r, echo = F}

# create list of dates to subset scenario's from (makes cleaner visualization)
scen_sub <- c('2040','2050','2060', '2070','2080','2030')
  
tmp <- thin_full %>% 
   filter(scen %in% scen_sub & level != 'historic') %>% 
  group_by(wyg, climproj, scen, level) %>% 
  summarise(
    mean = mean(precip),
    lower = quantile(precip, probs=0.1), 
    upper=quantile((precip), probs=0.90)
  ) 




precip_45 <- ggplot(tmp, aes(x=wyg, y=mean, group = level, color = level))+
  geom_line(alpha = .5) +
  geom_errorbar(aes(ymin= lower, ymax = upper), alpha = .5)  +
  # geom_line(data = tmp2, aes(x=tmp2$wyg, y=tmp2$mean, color = 'black'), alpha = .5) +
  # geom_errorbar(data = tmp2, aes(ymin= lower, ymax = upper, color = 'black'), alpha = .5)  +
  labs(y="Precipition (mm/yr)", x="Year after thin", fill="Precip (mm/yr)") + 
  facet_wrap(~scen, nrow=4) +
  labs(title = 'average precip data for rcp-4.5 rcp-8.5')

precip_45
```

***  
***  

## Carbon
##### Note: line is mean value for each climate 'level' (i.e historic, rcp-4.5, rcp-8.5) and error for all ribbon graphs:  +/- 2 sd (which, for the projections, includes all 4 models)

```{r plant carbon, echo=F}
plantc <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(plantc),
    sd = sd(plantc)
  )

plantc_plot <- ggplot(plantc, aes(x=wyg, y=mean, group = level, color = level, fill = level)) +
  geom_line()  +
  geom_hline(yintercept = plantc$mean[plantc$thin==100 & plantc$wyg == 0], color = 'darkgreen', size = 1) + # do we want to visually compare against starting value of the control, or the mean, or...?
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd, fill = level), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'mean plant carbon across models',
    title = 'change in plant carbon over time by thinning'
  )
plantc_plot
```
  
  
* 100 = 0% thinning
* reference bar set to amount of plant carbon in year 0 during the control (0% thinning)  
  
  
```{r stem carbon, echo = F}
stemc <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarise(
    mean = mean(stemc),
    sd = sd(stemc)
  )

stemc_plot <- ggplot(stemc, aes(x=wyg, y=mean, group = level, fill = level)) +
  geom_line() +
  geom_hline(yintercept = stemc$mean[stemc$thin==100 & stemc$wyg == 0], color = 'darkgreen', size = 1) + # do we want to visually compare against starting value of the control, or the mean, or...?
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=mean-2*sd, ymax=mean+2*sd), alpha = .3) +
  labs(
    x = 'years after thin',
    y = 'stem carbon',
    title = 'change in stem carbon over time by thinning %'
  )
stemc_plot
```


  
***  
***


## LAI



```{r lai scen, echo = F}

tmp <- base
tmp$scen <- recode(base$scen,
               "2035" = 1,
               "2040" = 2,
               '2045' = 3,
               '2050' = 4,
               '2055' = 5,
               '2060' = 6,
               '2065' = 7,
               '2070' = 8,
               '2075' = 9,
               '2080' = 10,
               '2085' = 11,
               '2090' = 12)

lai_scen <- ggplot(tmp, aes(x=wyg, y=lai, col = as.factor(thin)))+
  geom_line()+
  facet_wrap(~scen)+
  scale_color_manual(values=cc, labels = lbs)  +
  #theme(legend.position = 'none') +
  labs(
    x = 'years after thin',
    y = 'LAI',
    title = 'Change in LAI over time by starting year for historic data'
  )

lai_scen

```


```{r soil & ET, echo = F}
# base_et = jf_thin %>%
#   subset(canopy=="both" & thin == 100) %>%
#   group_by(soil) %>% summarize(et=mean(et))
# 
# pall_c = ggplot(subset(jf_thin, canopy=="both" & thin != 100), aes(x=wyg, y=et, col=as.factor(soil)))+facet_wrap(~thin) +stat_summary(fun.y="mean", geom="line")+ 
#   geom_hline(yintercept = base_et$et[1], colour="red")+
#  geom_hline(yintercept = base_et$et[3], colour="blue")+
#   geom_hline(yintercept = base_et$et[2], colour="green")
# 
# pall_c
```


```{r lai_thin, echo = F}
# variables through time

thin <- thin_full %>% 
  group_by(wyg, thin, level) %>% 
  summarize(meanlai=mean(lai), 
            sd=sd(lai))

lai_thin <- ggplot(thin, aes(x=wyg, y=meanlai, group = level, color = level)) +
  facet_wrap(~thin) +
  geom_ribbon(aes(ymin=meanlai-2*sd, ymax=meanlai+2*sd, fill = level), alpha=0.3) +
 geom_hline(yintercept = thin$meanlai[thin$thin == 100 & thin$wyg == 0], colour="darkgreen", size = 1)+
  labs(
    x = 'years since thin',
    y = 'Avg. LAI across scenarios',
    title = 'change in LAI over time based on thinning %'
  )

lai_thin

```
  
  ***  
  ***  
  
  
## ET

```{r ET, echo = F}
jf_thin_sub = subset(thin_full, thin_full$wyg %in% seq(0,80,10))


ET <- ggplot(jf_thin_sub, aes(x=as.factor(wyg), y=et, colour = level))+
  geom_boxplot(alpha = .5) + 
  facet_wrap(~thin) + 
  geom_hline(yintercept=0, col="grey", size=1) +
  labs(x="Year Since Thin", y="Change in ET (mm/yr)")
ET

```

```{r ET_scen, echo = F}
tmp <- filter(thin_full, scen %in% scen_sub)

ET_scen <- ggplot(tmp, aes(x=as.factor(thin), y=et, color = level))+
  geom_boxplot(outlier.size=NULL) + 
  facet_wrap(~scen) + 
  geom_hline(yintercept=0, col="grey", size=1) +
  labs(x="thinning %", y="Change in ET (mm/yr)")
ET_scen
```


## Respiration

```{r, echo = F}

resp <- ggplot(filter(jf_thin_sub, level == 'RCP-85'), aes(x=as.factor(wyg), y=resp))+
  geom_boxplot(outlier.size=NULL, color = 'blue') + 
  geom_boxplot(data = filter(jf_thin_sub, level == 'RCP-45'), outlier.size=NULL, color = 'red', alpha = .4) +
  facet_wrap(~thin) + 
  geom_hline(yintercept=0, col="grey", size=1) +
  #labs(x="Year Since Thin", y="Respiration", title = 'comparing change in respiration over time after thinning between rcp-4.5 & rcp-8.5')
resp

```